### ISSUE TITLE
Exception in typechecking of function makes the interpreter  hang

### ISSUE THREAD

**Issue by OlivierNicole** [nohtyprm/MrPython#101]
When typechecking the following function definition:
```python
def dessine_carre(x, y, c):
    """float*float*float -> Image
       hyp: c > 0
       dessine un carre de coté c dont le point en bas à gauche est de coordonnées (x, y)
    """
    fill_triangle(x, y, x+c, y, x, y+c, color="green")
    fill_triangle(x+c, y+c, x, y+c, x+c, y, color ="green")
    overlay(fill_triangle(x, y, x+c, y, x, y+c, color="green"), fill_triangle(x+c, y+c, x, y+c, x+c, y, color ="green"))
    return show_image(overlay(fill_triangle(x, y, x+c, y, x, y+c, color="green"), fill_triangle(x+c, y+c, x, y+c, x+c, y, color ="green")))
```
MrPython remains stuck, and the following backtrace appears on stderr:
```
Traceback (most recent call last):
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/PyInterpreter.py", line 45, in timer_callback
    ok, report = self.comm.recv()
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception in Tkinter callback
Traceback (most recent call last):
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/nix/store/k0igqpz995nmxwf6piyd5jjpcc7gcnyc-python3-3.7.4/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/PyInterpreter.py", line 75, in run_loop
    ok, report = interp.execute()
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/PyInterpreter.py", line 143, in execute
    ok = runner.execute(self.locals)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/StudentRunner.py", line 81, in execute
    if not self.check_rules(self.report):
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/StudentRunner.py", line 198, in check_rules
    if not self.check_types():
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/StudentRunner.py", line 243, in check_types
    type_ctx = typecheck_from_ast(self.AST, self.filename, self.source)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/typechecking/typechecker.py", line 2852, in typecheck_from_ast
    ctx = prog.type_check()
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/typechecking/typechecker.py", line 273, in type_check_Program
    fun_def.type_check(ctx)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/typechecking/typechecker.py", line 328, in type_check_FunctionDef
    instr.type_check(ctx)
  File "/home/olivier/enseignement/19_lu1in001/MrPython/mrpython/typechecking/typechecker.py", line 721, in type_check_ECall
    ctx.add_type_error(CallNotNoneError(enode, call_type))
NameError: name 'CallNotNoneError' is not defined
```

**Comment by fredokun** [comment]
In v.3.0.4  (current master, and commit https://github.com/nohtyprm/MrPython/commit/849b2ee780998bde766874acad996cbeacefe273) the bug does not occur anymore.

**Comment by OlivierNicole** [comment]
Thanks!
