### ISSUE TITLE
Cannot track side effects in tupled for loop

### ISSUE THREAD

**Issue by fredokun** [nohtyprm/MrPython#107]
The following program yields a fatal error :

```python
def f(L):
    """ list[tuple[str, int]] -> int """
    # s : str
    # k : int
    s,k = L[0]
    for u,v in L[1:]:
        if v > k:
            k = v
    return k
```

The problem is in the `for u, v in L[1:]:` bit ...
and the error raised is the following one:

```
Traceback (most recent call last):
  ...
  File "../mrpython/typechecking/typechecker.py", line 328, in type_check_FunctionDef
    instr.type_check(ctx)
  File "../mrpython/typechecking/typechecker.py", line 596, in type_check_For
    for_node.side_effect(ctx)
  File "../mrpython/typechecking/side_effects_utils.py", line 279, in side_effect_For
    
  File "../mrpython/typechecking/side_effects_utils.py", line 267, in assign_extended
    linearize(ctx, working_var, aliases)
  File "../mrpython/typechecking/side_effects_utils.py", line 250, in linearize
    tmp.access(str(i))
  File "../mrpython/typechecking/side_effects_utils.py", line 41, in access
    if c != p:
NotImplementedError: error in side-effect-checking, please report
```

**Comment by fredokun** [comment]
This is somewhat fixed in https://github.com/nohtyprm/MrPython/commit/f2c0c64da995755611387a821bf8926fcf5f861f

However, I think aliasing with tuples should be done as follows:

```python
for <var1>, <var2>, ...,  <varN> in  <iterable>:
   <body>
```

should be handled like : 

```python
for <dynvar> in  <iterable>:
   <var1>, <var2>, ...,  <varN> = <dynvar>
   <body>
```

Where `<dynvar>` is a gensym used only for the aliasing datastructure.
