### ISSUE TITLE
Python 3.11 / StudentRunner.py (v5) -> 'ValueError' object has no attribute 'lineno'

### ISSUE THREAD

**Issue by Nagisa19** [nohtyprm/MrPython#187]
In case the executed code has no error, we have an exception on python 3.11 on this line :

https://github.com/nohtyprm/MrPython/blame/382067b33bb0bcf18783496202fce6bfaee1dcf7/mrpython/StudentRunner.py#L208

**Comment by Nagisa19** [comment]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "MrPython/mrpython/StudentRunner.py", line 202, in run
    code = compile(self.AST, self.filename, 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: AST node line range (5, 3) is not valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "MrPython/mrpython/PyInterpreter.py", line 91, in run_loop
    ok, report = interp.execute()
                 ^^^^^^^^^^^^^^^^
  File "MrPython/mrpython/PyInterpreter.py", line 159, in execute
    ok = runner.execute(self.locals)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MrPython/mrpython/StudentRunner.py", line 112, in execute
    ret_val = self.run(locals, capture_stdout) # Run the code if it passed all the convention tests
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "MrPython/mrpython/StudentRunner.py", line 208, in run
    self.report.add_compilation_error('error', str(typ), err.lineno, err.offset, details=str(err))
                                                         ^^^^^^^^^^
AttributeError: 'ValueError' object has no attribute 'lineno'
```

**Comment by Nagisa19** [comment]
code to reproduce 
```python
import math

def aire_triangle(a: float,b: float,c: float) -> float:
    """ Number ** 3 -> float
    Hypothèse : (a>0) and (b>0) and (c>0)
    Hypothèse : les côtés a, b et c définissent bien un triangle.

    retourne l'aire du triangle dont les côtés sont de 
             longueurs a, b, et c."""

    p : float
    p = (a + b + c) / 2

    return math.sqrt(p * (p - a) * (p - b) * (p - c))

# Jeu de tests (Etape 3)
assert aire_triangle(13, 14, 15) == 84.0
assert aire_triangle(3, 4, 5) != 4.0 # bad test
assert aire_triangle(1, 1, 1) == math.sqrt(3 / 16)
assert aire_triangle(2, 3, 5) == 0.0  # c'est un triangle plat...
```

**Comment by fredokun** [comment]
this is problematic,  the `compile` primitive of Python 3.11 now checks line number ranges, which makes dynamic compilation of python code much more cumbersome.  As a workaround,   runtime checks of preconditions will be temporarily disabled in python >= 3.11.   Python 3.18 - 3.10  are recommended for now

**Comment by fredokun** [comment]
Temporary (un)fix in branch https://github.com/nohtyprm/MrPython/tree/py311unfix

**Comment by fredokun** [comment]
merged into master, but only because students use the latest version on master

**Comment by fredokun** [comment]
This is now solved
