### ISSUE TITLE
Evaluation bar: Pickle error with functions

### ISSUE THREAD

**Issue by Kerl13** [nohtyprm/MrPython#73]
Code:

```python
def f(x):
    """ int -> int """
    return x
```

If you try to "evaluate" `f` in the evaluation bar (just `f`, not `f(something)`), MrPython freezes and you get the following error message in the terminal:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
>     return self.func(*args)
>   File "/usr/lib/python3.7/tkinter/__init__.py", line 749, in callit
>     func(*args)
>   File "/home/martin/git/MrPython/mrpython/PyInterpreter.py", line 73, in run_loop
>     comm.send((ok, report))
>   File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
>     self._send_bytes(_ForkingPickler.dumps(obj))
>   File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
> _pickle.PicklingError: Can't pickle <function f at 0x7fd4b69f59d8>: attribute lookup f on __main__ failed

**Comment by fredokun** [comment]
... I think I can handle the problem by first type-checking the expression to evaluate, and prevent evaluation if it's not typed ... But this is a clear limitation of the pickler  (not to be able to send a function ...).
